zuul:
  routes:
    cart-service:
      path: /cart/**
      service-id: cart-service
      strip-prefix: false

    product-service:
      path: /products/**
      service-id: product-service
      strip-prefix: false

    coupon-service:
      path: /coupons/**
      service-id: coupon-service
      strip-prefix: false